### PR TITLE
Linux USE_OMP=True

### PR DESCRIPTION
**Pull request by ocefpaf**
@kwilcox do you use `pykdtree`? Want to be a maintainer? (This latest version is pretty fast!)

### CODE REVIEW

**Comment by jakirkham** [comment]
Maybe try setting `DYLD_FALLBACK_LIBRARY_PATH` to `$PREFIX/lib` on OS X?

**Comment by ocefpaf** [comment]
> Maybe try setting `DYLD_FALLBACK_LIBRARY_PATH` to `$PREFIX/lib` on OS X? 

You need to re-build numpy b/c of the `openblas` merge.

**Comment by jakirkham** [comment]
Yeah, I'm afraid you are right. Missed the `p`.

**Comment by jakirkham** [comment]
Added PR ( https://github.com/conda-forge/numpy-feedstock/pull/23 ) to rebuild 1.11.x and PR ( https://github.com/conda-forge/numpy-feedstock/pull/24 ) to rebuild 1.10.x. Going to have to go down the line with this probably.

**Comment by jakirkham** [comment]
NumPy has been deployed with a build against the now parallel OpenBLAS. Restarted the CI here.

**Comment by jakirkham** [comment]
Appears to now pass.

**Pull request merged**
