### PR TITLE
Add openmp for osx

### PR DESCRIPTION
**Pull request by cheginit**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by cheginit** [comment]
@conda-forge-admin, please rerender

**Comment by cheginit** [comment]
Following the discussion in #22, this PR tests using `llvm-openmp` to add `openmp` for `osx`.

**Comment by cheginit** [comment]
@ocefpaf It worked!

**Comment by djhoese** [comment]
I forget how this recipe handles the linux openmp, is it just provided by some other package or included by default? I don't see it in the dependencies. Would it be worth it to enable this dependency for all systems? How big is this package and all of its dependencies? Is it available on Windows?

**Comment by cheginit** [comment]
Based on my experience from maintaining other feedstocks, `libgomp` is usually used for `linux` and `llvm-openmp` for `osx`. So, technically, `libgomp` should be there, but I was also surprised that it's working without. I have seen some packages that use `llvm-openmp` for `win` too. So, I guess we can give a try here too.

**Comment by cheginit** [comment]
Awesome, it worked for Windows too! I checked the log for a `win` build [here](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=1077962&view=logs&j=1437f12d-1840-555e-1d60-298e0be353dc&t=e61a9fcc-abec-518f-6f56-33b467894cb6&l=1185) and it correctly picked `msvc` for OpenMP.

**Comment by djhoese** [comment]
Seems good to me. Thanks. If we can get opinions from @mraspaud that'd be great too just so I don't have to blame only myself if this fails :wink:

**Review by mraspaud — APPROVED** [review]
I don't understand all of it, but from what I get it looks good. Thanks for working on this!

**Pull request merged**
