### PR TITLE
[ci skip] adding user @djhoese + @mraspaud 

### LINKED ISSUE #41: @conda-forge-admin, please add user @djhoese
### Additional comment:

_No response_

### PR DESCRIPTION
**Pull request by conda-forge-linter**
Hi! This is the friendly automated conda-forge-webservice.

I've added user @djhoese as instructed in #41.

Merge this PR to add the user. Please do not rerender this PR or change it in any way. It has `[ci skip]` in the commit message to avoid pushing a new build and so the build configuration in the feedstock should not be changed.

Please contact [conda-forge/core](https://conda-forge.org/docs/maintainer/maintainer_faq.html#mfaq-contact-core) to have this PR merged, if the maintainer is unresponsive.

Fixes #41

### CODE REVIEW

**Comment by djhoese** [comment]
I'm a maintainer of pykdtree now (I made the 1.3.5 release that the other PR was created for). We could also add @mraspaud to the maintainers if he doesn't mind.

**Comment by djhoese** [comment]
Doesn't seem like the "ci skip" is doing anything.

**Comment by ngam** [comment]
> Doesn't seem like the "ci skip" is doing anything.

I will skip when the PR is merged, not here

**Comment by ngam** [comment]
Adding automerge for you, welcome aboard @djhoese!

**Comment by mraspaud** [comment]
I'm good with being a maintainer

**Pull request merged**
