### PR TITLE
add osxarm64 with higher compiler

### PR DESCRIPTION
**Pull request by ngam**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ngam** [comment]
@conda-forge-admin, please rerender

**Comment by ngam** [comment]
@conda-forge-admin, please rerender

**Comment by ngam** [comment]
@conda-forge-admin, please rerender

**Comment by ngam** [comment]
@ocefpaf the arm version of this is needed for some other package I am interested in. It was failing at `cython: command not found` and I tried playing with the compilers but to no avail. A fast workaround is just to disable the `cython` call during the arm cross-build (it is not done upstream anyway). I am not sure what that line does anyway `cython pykdtree/kdtree` in the build steps --- is it covered by [cykdtree](https://github.com/conda-forge/cykdtree-feedstock) by any chance?

**Comment by ocefpaf** [comment]
> I am not sure what that line does anyway `cython pykdtree/kdtree` in the build steps --- is it covered by [cykdtree](https://github.com/conda-forge/cykdtree-feedstock) by any chance?

That is a "re-cythoninzing" step to ensure we can build it on latest Python. When a new release is out we don't need it but we kept that anyway. If selecting produced a valid build we should be OK here.

**Pull request merged**
